export { SpecsPage } from './specs'
export { PluginsPage } from './plugins'
export { ArtifactsPage } from './artifacts'
export { ActivityPage } from './activity'
export { SettingsPage } from './settings'
export { LoginPage } from './login'
export { InitPage } from './init'
// Project pages
export { ProjectsPage } from './projects'
export { ProjectSpecsPage } from './project-specs'
export { ProjectPluginsPage } from './project-plugins'
export { ProjectBuildsPage } from './project-builds'
export { ProjectDeployPage } from './project-deploy'
export { ProjectSettingsPage } from './project-settings'
