export { SpecsPage } from './specs'
export { PluginsPage } from './plugins'
export { ArtifactsPage } from './artifacts'
export { ActivityPage } from './activity'
export { SettingsPage } from './settings'
export { LoginPage } from './login'
export { InitPage } from './init'
